//
// Created by admin on 2022/10/12.
//

#ifndef GLSAMPLE_RENDER_TYPE_H
#define GLSAMPLE_RENDER_TYPE_H

#define RENDER_TYPE  100
#define RENDER_TRIANGLE  RENDER_TYPE + 1
#define RENDER_RIPPLE  RENDER_TYPE + 2


#endif //GLSAMPLE_RENDER_TYPE_H
